export const Heroes = {
  Borcha: {
    COMPANION: "Borcha",
    DISLIKES_Conditions: "Heavy Losses",
    DISLIKES1: "Deshavi",
    DISLIKES2: "Ghazwan",
    DISLIKES_AS_EMISSARY: "Lezalit",
    LIKES: "Marnid",
    Noble: "",
    COSTS: "300",
    PARTY_SKILLS: "Tracking, Pathfinding, Spotting",
  },
  Marnid: {
    COMPANION: "Marnid",
    DISLIKES_Conditions:
      "Failing Quests, Returning Serfs, Robbing Villages/Caravans",
    DISLIKES1: "Baheshtur",
    DISLIKES2: "Nadia",
    DISLIKES_AS_EMISSARY: "Klethi",
    LIKES: "Borcha",
    Noble: "",
    COSTS: "Free",
    PARTY_SKILLS: "Wound Treatment, First Aid, Trade",
  },
  Ymira: {
    COMPANION: "Ymira",
    DISLIKES_Conditions: "Leaving Troops, Returning Serfs, Robbing Villages",
    DISLIKES1: "Odval",
    DISLIKES2: "Sajjad",
    DISLIKES_AS_EMISSARY: "Baheshtur",
    LIKES: "Alayen",
    Noble: "",
    COSTS: "Free",
    PARTY_SKILLS: "Wound Treatment, Surgery, First Aid, Trade",
  },
  Rolf: {
    COMPANION: "Rolf",
    DISLIKES_Conditions: "Retreating",
    DISLIKES1: "Bunduk",
    DISLIKES2: "Deshavi",
    DISLIKES_AS_EMISSARY: "Firentis",
    LIKES: "Sajjad",
    Noble: "Yes",
    COSTS: "300",
    PARTY_SKILLS: "Tactics, Surgery, First Aid",
  },
  Baheshtur: {
    COMPANION: "Baheshtur",
    DISLIKES_Conditions: "Hunger, Not Being Paid, Retreating, Heavy Casualties",
    DISLIKES1: "Marnid",
    DISLIKES2: "Katrin",
    DISLIKES_AS_EMISSARY: "Floris",
    LIKES: "Ghazwan",
    Noble: "Yes",
    COSTS: "400",
    PARTY_SKILLS: "",
  },
  Firentis: {
    COMPANION: "Firentis",
    DISLIKES_Conditions: "Failing Quests, Too Much Fighting, Robbing Villages",
    DISLIKES1: "Katrin",
    DISLIKES2: "Nizar",
    DISLIKES_AS_EMISSARY: "Matheld",
    LIKES: "Floris",
    Noble: "Yes",
    COSTS: "Free",
    PARTY_SKILLS: "Trainer",
  },
  Deshavi: {
    COMPANION: "Deshavi",
    DISLIKES_Conditions: "Hunger, Heavy Casualties",
    DISLIKES1: "Borcha",
    DISLIKES2: "Rolf",
    DISLIKES_AS_EMISSARY: "Edwyn",
    LIKES: "Klethi",
    Noble: "",
    COSTS: "300",
    PARTY_SKILLS: "Tracking, Pathfinding, Spotting",
  },
  Matheld: {
    COMPANION: "Matheld",
    DISLIKES_Conditions: "Retreating",
    DISLIKES1: "Jeremus",
    DISLIKES2: "Edwyn",
    DISLIKES_AS_EMISSARY: "Marnid",
    LIKES: "Nizar",
    Noble: "Yes",
    COSTS: "500",
    PARTY_SKILLS: "Tactics",
  },
  Alayen: {
    COMPANION: "Alayen",
    DISLIKES_Conditions: "Failing Quests",
    DISLIKES1: "Floris",
    DISLIKES2: "Odval",
    DISLIKES_AS_EMISSARY: "Borcha",
    LIKES: "Ymira",
    Noble: "Yes",
    COSTS: "300",
    PARTY_SKILLS: "Tactics",
  },
  Bunduk: {
    COMPANION: "Bunduk",
    DISLIKES_Conditions: "Heavy Casualties, Robbing Villages",
    DISLIKES1: "Rolf",
    DISLIKES2: "Lezalit",
    DISLIKES_AS_EMISSARY: "Deshavi",
    LIKES: "Katrin",
    Noble: "",
    COSTS: "200",
    PARTY_SKILLS: "Trainer, Tactics, First Aid",
  },
  Katrin: {
    COMPANION: "Katrin",
    DISLIKES_Conditions: "Hunger, Not Being Paid, Heavy Casualties",
    DISLIKES1: "Firentis",
    DISLIKES2: "Baheshtur",
    DISLIKES_AS_EMISSARY: "Artimenner",
    LIKES: "Bunduk",
    Noble: "",
    COSTS: "100",
    PARTY_SKILLS: "Foraging, Wound Treatment, First Aid, Trade",
  },
  Jeremus: {
    COMPANION: "Jeremus",
    DISLIKES_Conditions: "Too Much Fighting, Returning Serfs, Robbing Villages",
    DISLIKES1: "Matheld",
    DISLIKES2: "Artimenner",
    DISLIKES_AS_EMISSARY: "Nizar",
    LIKES: "Odval",
    Noble: "",
    COSTS: "Free",
    PARTY_SKILLS: "Wound Treatment, Surgery, First Aid, Trade",
  },
  Nizar: {
    COMPANION: "Nizar",
    DISLIKES_Conditions: "Retreating",
    DISLIKES1: "Nadia",
    DISLIKES2: "Firentis",
    DISLIKES_AS_EMISSARY: "Bunduk",
    LIKES: "Matheld",
    Noble: "",
    COSTS: "300",
    PARTY_SKILLS: "",
  },
  Lezalit: {
    COMPANION: "Lezalit",
    DISLIKES_Conditions: "",
    DISLIKES1: "Edwyn",
    DISLIKES2: "Bunduk",
    DISLIKES_AS_EMISSARY: "Katrin",
    LIKES: "Artimenner",
    Noble: "Yes",
    COSTS: "400",
    PARTY_SKILLS: "Trainer",
  },
  Artimenner: {
    COMPANION: "Artimenner",
    DISLIKES_Conditions: "Hunger, Failing Quests, Heavy Casualties",
    DISLIKES1: "Ghazwan",
    DISLIKES2: "Jeremus",
    DISLIKES_AS_EMISSARY: "Rolf",
    LIKES: "Lezalit",
    Noble: "",
    COSTS: "300",
    PARTY_SKILLS: "Tracking, Tactics, Spotting, Engineer, Trade",
  },
  Klethi: {
    COMPANION: "Klethi",
    DISLIKES_Conditions: "Retreating",
    DISLIKES1: "Sajjad",
    DISLIKES2: "Floris",
    DISLIKES_AS_EMISSARY: "Jeremus",
    LIKES: "Deshavi",
    Noble: "",
    COSTS: "200",
    PARTY_SKILLS: "Tracking, Pathfinding, Spotting",
  },
  Floris: {
    COMPANION: "Floris",
    DISLIKES_Conditions: "Hunger,Heavy Casualties",
    DISLIKES1: "Klethi",
    DISLIKES2: "Alayen",
    DISLIKES_AS_EMISSARY: "Ghazwan",
    LIKES: "Firentis",
    Noble: "Yes",
    COSTS: "20,000",
    PARTY_SKILLS: "Trainer, Tracking, Tactics, Pathfinding, Trade",
  },
  Nadia: {
    COMPANION: "Nadia",
    DISLIKES_Conditions: "Returning Serfs, Robbing Villages, Failing Quests",
    DISLIKES1: "Marnid",
    DISLIKES2: "Nizar",
    DISLIKES_AS_EMISSARY: "Alayen",
    LIKES: "Edwyn",
    Noble: "",
    COSTS: "Free",
    PARTY_SKILLS: "",
  },
  Odval: {
    COMPANION: "Odval",
    DISLIKES_Conditions: "Hunger, Not Being Paid",
    DISLIKES1: "Ymira",
    DISLIKES2: "Alayen",
    DISLIKES_AS_EMISSARY: "Sajjad",
    LIKES: "Jeremus",
    Noble: "",
    COSTS: "200",
    PARTY_SKILLS: "Tracking, Pathfinding, Spotting",
  },
  Sajjad: {
    COMPANION: "Sajjad",
    DISLIKES_Conditions: "Hunger, Not Being Paid, Failing Quests",
    DISLIKES1: "Ymira",
    DISLIKES2: "Klethi",
    DISLIKES_AS_EMISSARY: "Nadia",
    LIKES: "Rolf",
    Noble: "",
    COSTS: "300",
    PARTY_SKILLS: "",
  },
  Ghazwan: {
    COMPANION: "Ghazwan",
    DISLIKES_Conditions: "Robbing Villages, Retreating",
    DISLIKES1: "Borcha",
    DISLIKES2: "Artimenner",
    DISLIKES_AS_EMISSARY: "Odval",
    LIKES: "Baheshtur",
    Noble: "Yes",
    COSTS: "400",
    PARTY_SKILLS: "Tactics, Spotting, Trade",
  },
  Edwyn: {
    COMPANION: "Edwyn",
    DISLIKES_Conditions: "Robbing Villages, Failing Quests",
    DISLIKES1: "Matheld",
    DISLIKES2: "Lezalit",
    DISLIKES_AS_EMISSARY: "Ymira",
    LIKES: "Nadia",
    Noble: "",
    COSTS: "300",
    PARTY_SKILLS: "Tracking, Pathfinding, Spotting, Trade",
  },
};

export const Nobles = Object.keys(Heroes).filter((key) => Heroes[key].Noble);